# docker-compose.yml
version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./scripts/init.sql/:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: eyemobileapi
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080